---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: reacttutorial.l www.reacttutorial.l 192.168.56.101
    timezone: America/Toronto
  vars_files:
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - composer
    - phpcommon
    - app
